name: Docker Release

on:
  # Trigger the workflow on the new 'v*' tag created
  push:
    tags:
      - "v*"
    branches:
      - "*"
  pull_request:
    branches: [master]
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "8.10"
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test only (without release)
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.version }}/buster
          file: ${{ matrix.version }}/buster/Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          tags: |
            haskell/haskell:${{ matrix.version }}
